{
  "hash": "e5021369cca75c4d5b1c0a51621ac713",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Time spent on manual pit emptying jobs in Mzuzu, Malawi: total job time and travel to the disposal site\"\nauthor:\n  - name: Padraic Casserly\n    email: pcasserly@ethz.ch\n    affiliations:\n      - name: Global Health Engineering, ETH Zürich\ndate: 2026-09-29\nbibliography: references.bib\nabstract: |\n  We use task-level timing data recorded with the Gulper Timer app during\n  ridealong observations of manual pit latrine emptying in Mzuzu, Malawi, to\n  answer two questions that time-driven activity-based costing (TDABC) needs\n  answered first: how much time is spent on a pit emptying job in total, and\n  how much of a job is spent travelling to the sludge disposal site when the\n  team makes such a trip. Time is reported in two ways throughout: labour\n  time (person-hours, every worker's recorded time added together) and\n  elapsed time (clock hours, with simultaneous work by several workers\n  counted once).\neditor:\n  markdown:\n    wrap: 72\n---\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'dplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(readr)\nlibrary(ggplot2)\nlibrary(knitr)\n\ntasks <- read_csv(\"../../data/all_tasks_clean.csv\", show_col_types = FALSE)\n\nfmt <- function(x, digits = 1) format(round(x, digits), nsmall = digits, big.mark = \",\", trim = TRUE)\n\n# ---- Jobs: labour time and elapsed time -------------------------------------\n# Elapsed time is the span from first start to last end on each recorded day;\n# one job was recorded over two days, so its daily spans are added.\nday_spans <- tasks |>\n  group_by(job_id, date) |>\n  summarise(span_h = as.numeric(max(entry_end_time) - min(entry_start_time)) / 3600,\n            .groups = \"drop\")\n\njobs <- tasks |>\n  group_by(job_id) |>\n  summarise(\n    date = min(date),\n    n_days = n_distinct(date),\n    n_workers = n_distinct(gulper_id),\n    n_entries = n(),\n    labour_h = sum(duration_seconds) / 3600,\n    .groups = \"drop\"\n  ) |>\n  left_join(day_spans |> group_by(job_id) |> summarise(elapsed_h = sum(span_h), .groups = \"drop\"),\n            by = \"job_id\") |>\n  arrange(date, job_id) |>\n  group_by(date) |>\n  mutate(job_label = if (n() > 1) paste0(format(date, \"%Y-%m-%d\"), \" (\", row_number(), \")\")\n                     else format(date, \"%Y-%m-%d\")) |>\n  ungroup()\n\ntotal_labour_h <- sum(jobs$labour_h)\ntotal_elapsed_h <- sum(jobs$elapsed_h)\nn_jobs <- nrow(jobs)\nn_workers <- n_distinct(tasks$gulper_id)\nn_entries <- nrow(tasks)\nrest_h <- sum(tasks$duration_seconds[tasks$task == \"Rest\"]) / 3600\n\n# Sensitivity: the entries flagged timer_suspect capped at 50 minutes\ncapped_labour_h <- tasks |>\n  mutate(d = if_else(grepl(\"timer_suspect\", flags), pmin(duration_seconds, 3000), duration_seconds)) |>\n  summarise(h = sum(d) / 3600) |>\n  pull(h)\nn_suspect <- sum(grepl(\"timer_suspect\", tasks$flags))\n\n# ---- Travel to the disposal site ------------------------------------------\nerrands <- tasks |> filter(task == \"Travel\", subtask == \"On errand\")\nmin_trip_min <- 5\n\ntravel <- tasks |>\n  filter(task == \"Travel\", subtask == \"Travel to disposal site\") |>\n  mutate(s = as.numeric(entry_start_time), e = as.numeric(entry_end_time)) |>\n  arrange(job_id, s) |>\n  group_by(job_id) |>\n  mutate(prev_end = lag(cummax(e), default = -Inf), trip = cumsum(s > prev_end)) |>\n  ungroup()\n\ntrips_all <- travel |>\n  group_by(job_id, trip) |>\n  summarise(start = min(s), end = max(e), gulpers = n_distinct(gulper_id),\n            entries = n(), labour_h = sum(duration_seconds) / 3600, .groups = \"drop\") |>\n  mutate(clock_min = (end - start) / 60, keep = clock_min >= min_trip_min)\ntrips <- trips_all |> filter(keep)\nshort <- trips_all |> filter(!keep)\n\nsummarise_travel <- function(tr) {\n  tr |>\n    group_by(job_id) |>\n    summarise(trips = n(), gulpers = max(gulpers),\n              travel_clock_h = sum(end - start) / 3600,\n              travel_labour_h = sum(labour_h), .groups = \"drop\") |>\n    left_join(jobs |> select(job_id, date, job_label, labour_h), by = \"job_id\") |>\n    mutate(share = 100 * travel_labour_h / labour_h) |>\n    arrange(date, job_id)\n}\ntravel_jobs <- summarise_travel(trips)\ntravel_jobs_unfiltered <- summarise_travel(trips_all)\n\nn_travel_jobs <- nrow(travel_jobs)\nn_trips <- nrow(trips)\nmean_clock_h <- mean(travel_jobs$travel_clock_h)\nmedian_clock_h <- median(travel_jobs$travel_clock_h)\nmean_travel_labour_h <- mean(travel_jobs$travel_labour_h)\nmedian_travel_labour_h <- median(travel_jobs$travel_labour_h)\nmean_trip_min <- mean(trips$clock_min)\nmean_gulpers_trip <- mean(trips$gulpers)\nratio <- sum(travel_jobs$travel_labour_h) / sum(travel_jobs$travel_clock_h)\ntravel_share_total <- 100 * sum(travel_jobs$travel_labour_h) / total_labour_h\n\n# Shared plot styling\nbar_theme <- function() {\n  theme_minimal(base_size = 10) +\n    theme(\n      panel.grid.major.y = element_blank(),\n      panel.grid.minor = element_blank(),\n      axis.text = element_text(colour = \"#52514e\"),\n      plot.margin = margin(12, 8, 4, 4)\n    )\n}\n```\n:::\n\n\n# Introduction\n\nTime-driven activity-based costing (TDABC) allocates costs to activities\nbased on the time resources spend on them. A first step is therefore to\nestablish how much time the service being costed consumes, and how that\ntime is split between activities that every job needs and activities\nthat only some jobs need. Manual pit emptying in Mzuzu involves not only\nemptying the pit but, for some jobs, transporting the extracted sludge\nto a disposal site, an activity that takes the whole team away from the\nsite. This manuscript answers two questions:\n\n1. **What is the total amount of time spent on pit emptying jobs?**\n2. **What is the average time spent per job travelling to the disposal\n   site, when a team travels to the disposal site?**\n\n# Data and methods\n\n## Data\n\nThe dataset (`data/all_tasks_clean.csv`) contains 10,778\ntask entries recorded for 36 pit emptying jobs between\n08 May 2026 and\n14 September 2026, performed by 19\nanonymised pit emptiers (\"gulpers\"). Each entry records one worker\nperforming one task (e.g. Fluidizing, Extraction, Rest) with a start\ntime, end time and duration in seconds.\n\nThe file is the cleaned version of the raw app export, produced by\n`data-review/clean.R` and documented in `data-review/README.md`.\nRelative to the raw export, six accidental taps shorter than 2 seconds\nwere dropped, the Equipment subtask \"Repair\" was recoded to \"Repairing\",\nand job identities were corrected from field knowledge: the recordings\nfiled as 2026-06-12_01 and 2026-06-13_01 are one job carried out over\ntwo days by two crews, and the two recording sessions filed under\n2026-06-14_02 are two separate jobs. The file has no missing values\nexcept `subtask`, which is empty by design for the Rest and Disposal\ntasks, and recorded durations agree with the difference between end and\nstart times to within ±1 second. Sixteen entries longer than 50 minutes\nare kept as recorded; 4 of them, in one job, look like\ntimers left running over a break and are used in a sensitivity check.\nJobs are identified below by their date; where two jobs were recorded on\nthe same day they are numbered (1) and (2).\n\n## Two measures of time\n\nSeveral gulpers usually work simultaneously on the same job, so \"time\nspent\" is measured in two ways throughout:\n\n- **Labour time (person-hours):** the sum of `duration_seconds` over all\n  entries, i.e. every worker's recorded time added together. This is the\n  measure relevant for TDABC, where labour capacity is the resource\n  being costed.\n- **Elapsed time (clock hours):** for each job, the interval from the\n  earliest `entry_start_time` to the latest `entry_end_time` on each\n  recorded day, summed across days and jobs. This measures how long the\n  jobs took on the calendar.\n\nAll recorded tasks, including Rest, Communication and in-job Travel, are\ncounted as time spent on the job. Travel from the gulpers' base to the\njob site is not among the recorded tasks.\n\n## Travel to the disposal site\n\nThe Travel task has two subtasks: *On errand*, for short in-job errands,\nand *Travel to disposal site*, for transporting sludge away from the\nsite. Only the second is analysed for question 2; the 104\nerrand entries (15.5\nperson-hours in 23 jobs) remain part of\ntotal job time but are not counted as disposal travel.\n\nGulpers travel to the disposal site together, so each trip appears in\nthe data as several near-identical entries, one per worker. Within each\njob, entries that overlap in time are merged into a single **trip**\nrunning from the earliest start to the latest end. A job's elapsed\ntravel time is the summed duration of its trips, counting a trip made by\nfour gulpers once; its labour travel time adds every gulper's entry.\n\nThe population for question 2 is the set of jobs in which the team\ntravelled to the disposal site. Genuine trips last\n28–46\nminutes. A few disposal-site entries are far shorter and cannot\nrepresent a trip: 3 merged intervals of under\n5 minutes\n(3, 42, 69\nseconds), each recorded by one or two workers. These are treated as\naccidental taps and dropped, which removes\n3.0 person-minutes. One job has only such\nan entry and therefore does not count as a job with a disposal trip.\n\n# Results\n\n## Total time spent on pit emptying jobs\n\nAcross the 36 observed jobs, gulpers spent a total of\n**509.0 person-hours** on pit emptying. The jobs took\na total of **143.6 elapsed clock hours**, so on\naverage 3.5 gulpers' worth of time\nwas being recorded at any moment of a job. Per job, the mean labour time\nwas 14.1 person-hours (median\n11.0, range\n2.4–58.2) and the mean\nelapsed time was 4.0 hours (median\n3.6, range\n0.8–9.7).\n\n@tbl-task breaks the labour time down by main task. Rest is the largest\nsingle category (150.4 person-hours,\n29.5 % of the total).\n\n\n::: {#tbl-task .cell tbl-cap='Labour time by main task, summed over all 36 jobs.'}\n\n```{.r .cell-code .hidden}\ntasks |>\n  group_by(Task = task) |>\n  summarise(Entries = n(), `Person-hours` = sum(duration_seconds) / 3600, .groups = \"drop\") |>\n  arrange(desc(`Person-hours`)) |>\n  mutate(`Share (%)` = 100 * `Person-hours` / sum(`Person-hours`)) |>\n  bind_rows(tibble(Task = \"Total\", Entries = n_entries,\n                   `Person-hours` = total_labour_h, `Share (%)` = 100)) |>\n  kable(digits = 1, format.args = list(big.mark = \",\"))\n```\n\n::: {.cell-output-display}\n\n\n|Task            | Entries| Person-hours| Share (%)|\n|:---------------|-------:|------------:|---------:|\n|Rest            |   3,101|        150.4|      29.5|\n|Earthworks      |   1,098|         69.7|      13.7|\n|Fluidizing      |   1,470|         63.5|      12.5|\n|Equipment       |   1,352|         62.9|      12.4|\n|Extraction      |   1,381|         62.9|      12.4|\n|Travel          |     147|         36.2|       7.1|\n|Communication   |   1,342|         25.1|       4.9|\n|Superstructure  |     371|         16.6|       3.3|\n|Disposal        |     256|         14.2|       2.8|\n|Sludge handling |     260|          7.5|       1.5|\n|Total           |  10,778|        509.0|     100.0|\n\n\n:::\n:::\n\n\n@fig-task shows the same breakdown, with tasks coloured by the kind of\nwork they belong to.\n\n\n::: {#cell-fig-task .cell}\n\n```{.r .cell-code .hidden}\ntask_groups <- c(\n  Fluidizing        = \"Emptying the pit\",\n  Extraction        = \"Emptying the pit\",\n  `Sludge handling` = \"Emptying the pit\",\n  Disposal          = \"Emptying the pit\",\n  Earthworks        = \"Site and structure works\",\n  Superstructure    = \"Site and structure works\",\n  Equipment         = \"Support tasks\",\n  Communication     = \"Support tasks\",\n  Travel            = \"Support tasks\",\n  Rest              = \"Rest\"\n)\ngroup_colours <- c(\n  \"Emptying the pit\"         = \"#2a78d6\",\n  \"Site and structure works\" = \"#eb6834\",\n  \"Support tasks\"            = \"#1baf7a\",\n  \"Rest\"                     = \"#4a3aa7\"\n)\n\ntask_summary <- tasks |>\n  group_by(task) |>\n  summarise(hours = sum(duration_seconds) / 3600, .groups = \"drop\") |>\n  mutate(\n    share = 100 * hours / sum(hours),\n    group = factor(task_groups[task], levels = names(group_colours)),\n    task = reorder(task, hours),\n    label = paste0(fmt(hours), \" h (\", fmt(share), \" %)\")\n  )\n\nggplot(task_summary, aes(x = hours, y = task, fill = group)) +\n  geom_col(width = 0.72) +\n  geom_text(aes(label = label), hjust = -0.08, size = 3, colour = \"#52514e\") +\n  scale_fill_manual(values = group_colours, name = NULL) +\n  scale_x_continuous(expand = expansion(mult = c(0, 0.28))) +\n  labs(x = \"Labour time (person-hours)\", y = NULL) +\n  bar_theme() +\n  theme(\n    legend.position = \"top\",\n    legend.justification = \"left\",\n    legend.key.size = unit(0.4, \"cm\"),\n    axis.text.y = element_text(colour = \"#0b0b0b\", size = 10)\n  )\n\ngroup_hours <- tapply(task_summary$hours, task_summary$group, sum)\n```\n\n::: {.cell-output-display}\n![Labour time by main task across all 36 jobs, coloured by activity group. Labels give person-hours and share of total labour time.](index_files/figure-docx/fig-task-1.png){#fig-task}\n:::\n:::\n\n\nGrouped this way, the tasks that directly empty the pit (fluidizing,\nextraction, sludge handling and disposal) account for\n148.1 person-hours\n(29.1 %),\nabout the same as Rest (150.4 person-hours).\nSupport tasks take 124.2 person-hours\n(24.4 %) and\nsite and structure works\n86.3 person-hours\n(16.9\n%).\n\n@fig-jobs shows the labour time of each job. Labour time varies widely\nbetween jobs; @tbl-jobs in the appendix lists the values for every job.\n\n\n::: {#cell-fig-jobs .cell}\n\n```{.r .cell-code .hidden}\njobs |>\n  mutate(job_label = factor(job_label, levels = rev(job_label))) |>\n  ggplot(aes(x = labour_h, y = job_label)) +\n  geom_col(fill = \"#2a78d6\", width = 0.7) +\n  geom_vline(xintercept = mean(jobs$labour_h), linetype = \"dashed\", colour = \"#52514e\") +\n  annotate(\"text\", x = mean(jobs$labour_h), y = n_jobs + 0.6,\n           label = paste0(\"mean \", fmt(mean(jobs$labour_h)), \" h\"),\n           hjust = -0.05, size = 3, colour = \"#52514e\") +\n  scale_x_continuous(expand = expansion(mult = c(0, 0.05))) +\n  coord_cartesian(clip = \"off\") +\n  labs(x = \"Labour time (person-hours)\", y = NULL) +\n  bar_theme()\n```\n\n::: {.cell-output-display}\n![Labour time (person-hours) per pit emptying job, ordered by date. The dashed line is the mean.](index_files/figure-docx/fig-jobs-1.png){#fig-jobs}\n:::\n:::\n\n\n## Time spent travelling to the disposal site\n\nA team travelled to the disposal site in **7 of the\n36 observed jobs**, making 11 trips in total. In those\njobs, the team spent on average **0.9 clock hours\n(52 minutes) per job travelling to the\ndisposal site** (median 0.6 hours, range\n0.5–1.7).\nIn labour time this is 3.0 person-hours per\njob (median 2.2, range\n0.9–6.0).\n\nA job with a disposal trip had 1.6 trips\non average, each lasting 33 minutes and made by\n3.4 gulpers together, so labour time is\n3.4 times elapsed time. Within these jobs, disposal travel\ntook up 17 % of the job's labour time\non average (range\n9–24\n%). Across all 36 jobs, disposal travel accounts for\n4.1 % of the 509.0\nperson-hours recorded. @tbl-travel lists each job with a trip and\n@fig-travel shows the elapsed travel time per job.\n\n\n::: {#tbl-travel .cell tbl-cap='Disposal-site travel for each job in which a trip was made. Elapsed time counts a trip once regardless of how many gulpers made it; labour time adds every gulper\\'s travel. Share is labour travel time as a percentage of the job\\'s total labour time.'}\n\n```{.r .cell-code .hidden}\nsummary_row <- function(label, f) {\n  tibble(\n    `Job Date` = label,\n    Trips = fmt(f(travel_jobs$trips)), Gulpers = fmt(f(travel_jobs$gulpers)),\n    `Elapsed (h)` = f(travel_jobs$travel_clock_h),\n    `Labour (person-h)` = f(travel_jobs$travel_labour_h),\n    `Share of job (%)` = f(travel_jobs$share)\n  )\n}\n\ntravel_jobs |>\n  transmute(\n    `Job Date` = job_label,\n    Trips = as.character(trips),\n    Gulpers = as.character(gulpers),\n    `Elapsed (h)` = travel_clock_h,\n    `Labour (person-h)` = travel_labour_h,\n    `Share of job (%)` = share\n  ) |>\n  bind_rows(summary_row(\"Mean\", mean), summary_row(\"Median\", median)) |>\n  kable(digits = 1, align = \"lrrrrr\")\n```\n\n::: {.cell-output-display}\n\n\n|Job Date       | Trips| Gulpers| Elapsed (h)| Labour (person-h)| Share of job (%)|\n|:--------------|-----:|-------:|-----------:|-----------------:|----------------:|\n|2026-05-08     |     1|       2|         0.5|               0.9|             19.2|\n|2026-08-08     |     3|       4|         1.7|               6.0|             17.0|\n|2026-08-11     |     1|       4|         0.6|               2.2|             14.0|\n|2026-08-20 (1) |     1|       4|         0.5|               1.9|              9.3|\n|2026-09-08     |     2|       4|         1.3|               5.4|             16.1|\n|2026-09-13 (2) |     1|       2|         0.5|               1.0|             16.9|\n|2026-09-14 (2) |     2|       3|         1.1|               3.2|             23.5|\n|Mean           |   1.6|     3.3|         0.9|               3.0|             16.6|\n|Median         |   1.0|     4.0|         0.6|               2.2|             16.9|\n\n\n:::\n:::\n\n\n\n::: {#cell-fig-travel .cell}\n\n```{.r .cell-code .hidden}\ntravel_jobs |>\n  mutate(\n    job_label = factor(job_label, levels = rev(job_label)),\n    label = paste0(trips, ifelse(trips == 1, \" trip\", \" trips\"))\n  ) |>\n  ggplot(aes(x = travel_clock_h, y = job_label)) +\n  geom_col(fill = \"#2a78d6\", width = 0.7) +\n  geom_text(aes(label = label), hjust = -0.15, size = 3, colour = \"#52514e\") +\n  geom_vline(xintercept = mean_clock_h, linetype = \"dashed\", colour = \"#52514e\") +\n  annotate(\"text\", x = mean_clock_h, y = n_travel_jobs + 0.7,\n           label = paste0(\"mean \", fmt(mean_clock_h), \" h\"),\n           hjust = -0.05, size = 3, colour = \"#52514e\") +\n  scale_x_continuous(expand = expansion(mult = c(0, 0.15))) +\n  coord_cartesian(clip = \"off\") +\n  labs(x = \"Elapsed travel time (clock hours)\", y = NULL) +\n  bar_theme()\n```\n\n::: {.cell-output-display}\n![Elapsed time spent travelling to the disposal site per job, for the jobs in which a trip was made, ordered by date. Labels give the number of trips. The dashed line is the mean.](index_files/figure-docx/fig-travel-1.png){#fig-travel}\n:::\n:::\n\n\nTravel time per job is driven mainly by the number of trips: jobs with\none trip take about half an hour of elapsed time, and the two jobs with\nthe most travel\n(2026-08-08 and 2026-09-08)\nmade\n3 and 2\ntrips respectively.\n\n## Sensitivity checks\n\nCapping the 4 entries that look like timers left running at\n50 minutes would lower the total labour time to\n506.8 person-hours, a change of\n2.2 person-hours\n(0.4 %).\nKeeping the short disposal-site entries dropped in the Methods adds one\njob and changes the mean elapsed travel time to\n0.8 hours over\n8 jobs\n(2.6 person-hours);\nthis is lower only because the added job contributes a\n0.7-minute\nentry.\n\n# Conclusion\n\nThe 36 observed pit emptying jobs consumed\n**509.0 person-hours** of recorded labour\n(143.6 elapsed clock hours), a mean of\n14.1 person-hours per job. When a team travels\nto the disposal site, which happened in 7 of the\n36 jobs, it spends on average **0.9 clock\nhours (52 minutes) per job** on that travel,\ncorresponding to **3.0 person-hours** of\nlabour because 3.4 gulpers travel together. A\nsingle trip takes about 33 minutes, and jobs vary\nmainly in how many trips they need. For TDABC purposes the person-hour\nfigures are the quantities to cost: total labour time applies to every\njob, and disposal travel should be added only to the jobs that require a\ntrip.\n\n# Appendix A: Job-level results {.appendix}\n\n\n::: {#tbl-jobs .cell tbl-cap='Workers, labour time, elapsed time and disposal-site travel for each job. Travel columns are blank for jobs without a trip.'}\n\n```{.r .cell-code .hidden}\noptions(knitr.kable.NA = \"\")\njobs |>\n  left_join(travel_jobs |> select(job_id, travel_clock_h, travel_labour_h), by = \"job_id\") |>\n  transmute(\n    `Job Date` = job_label,\n    Gulpers = n_workers,\n    Entries = n_entries,\n    `Labour (person-h)` = labour_h,\n    `Elapsed (h)` = elapsed_h,\n    `Travel elapsed (h)` = travel_clock_h,\n    `Travel labour (person-h)` = travel_labour_h\n  ) |>\n  bind_rows(tibble(\n    `Job Date` = \"Total\", Gulpers = n_workers, Entries = n_entries,\n    `Labour (person-h)` = total_labour_h, `Elapsed (h)` = total_elapsed_h,\n    `Travel elapsed (h)` = sum(travel_jobs$travel_clock_h),\n    `Travel labour (person-h)` = sum(travel_jobs$travel_labour_h)\n  )) |>\n  kable(digits = 1, format.args = list(big.mark = \",\"))\n```\n\n::: {.cell-output-display}\n\n\n|Job Date       | Gulpers| Entries| Labour (person-h)| Elapsed (h)| Travel elapsed (h)| Travel labour (person-h)|\n|:--------------|-------:|-------:|-----------------:|-----------:|------------------:|------------------------:|\n|2026-05-08     |       2|     162|               4.9|         2.5|                0.5|                      0.9|\n|2026-05-21     |       2|     120|               2.7|         1.5|                   |                         |\n|2026-05-31     |       1|      91|               2.8|         2.9|                   |                         |\n|2026-06-12     |       8|   1,514|              38.5|         7.7|                   |                         |\n|2026-06-13     |       3|     241|               7.0|         2.3|                   |                         |\n|2026-06-14 (1) |       4|     455|              27.0|         8.3|                   |                         |\n|2026-06-14 (2) |       3|     731|              12.3|         4.2|                   |                         |\n|2026-06-16     |       3|     199|              10.9|         3.7|                   |                         |\n|2026-06-18     |       3|      71|               5.2|         1.7|                   |                         |\n|2026-06-22     |       4|     159|              11.2|         2.8|                   |                         |\n|2026-06-29     |       4|     228|              21.1|         6.1|                   |                         |\n|2026-07-03     |       4|     295|              16.6|         4.4|                   |                         |\n|2026-07-09     |       4|     340|              18.5|         5.5|                   |                         |\n|2026-07-13     |       3|     175|               7.9|         2.6|                   |                         |\n|2026-07-27     |       4|     511|              14.9|         4.5|                   |                         |\n|2026-07-29     |       3|     347|               6.6|         2.2|                   |                         |\n|2026-07-31     |       4|     455|              14.3|         3.6|                   |                         |\n|2026-08-03     |       3|     199|              13.7|         4.6|                   |                         |\n|2026-08-08     |       4|     651|              35.3|         9.7|                1.7|                      6.0|\n|2026-08-11     |       4|     403|              15.8|         4.0|                0.6|                      2.2|\n|2026-08-20 (1) |       4|     290|              21.0|         6.2|                0.5|                      1.9|\n|2026-08-20 (2) |       4|     270|              10.1|         2.5|                   |                         |\n|2026-08-22 (1) |       4|     224|               6.9|         2.0|                   |                         |\n|2026-08-22 (2) |       4|     375|              15.7|         3.9|                   |                         |\n|2026-08-23     |       4|     213|              14.3|         3.6|                   |                         |\n|2026-08-25 (1) |       3|      35|               2.4|         0.8|                   |                         |\n|2026-08-25 (2) |       3|      74|               2.6|         0.9|                   |                         |\n|2026-08-27 (1) |       4|     220|              10.3|         4.4|                   |                         |\n|2026-08-27 (2) |       3|     151|               9.0|         3.0|                   |                         |\n|2026-08-28     |       3|     224|               8.5|         2.8|                   |                         |\n|2026-09-03     |       7|     628|              58.2|         8.4|                   |                         |\n|2026-09-08     |       4|     377|              33.4|         8.4|                1.3|                      5.4|\n|2026-09-13 (1) |       2|      54|               2.4|         1.2|                   |                         |\n|2026-09-13 (2) |       2|     103|               5.7|         2.9|                0.5|                      1.0|\n|2026-09-14 (1) |       3|      92|               7.9|         3.2|                   |                         |\n|2026-09-14 (2) |       3|     101|              13.7|         4.6|                1.1|                      3.2|\n|Total          |      19|  10,778|             509.0|       143.6|                6.1|                     20.7|\n\n\n:::\n:::\n\n\n# Appendix B: Relevant literature {.appendix}\n\nThe five references in the author's Zotero library most relevant to this\ndataset, with one sentence on why each matters here:\n\n1.  @yesaya2021cost apply time-driven activity-based costing to compost\n    production in Blantyre, Malawi, making it the closest methodological\n    precedent for turning task-level timing data like these into\n    activity costs.\n2.  @wilcox2026formal analyse the costs of 23 formal manual emptying\n    providers in Malawi and Uganda and find labour is what makes manual\n    emptying expensive, which is why the person-hours measured here, for\n    the whole job and for disposal travel, are the key costing inputs.\n3.  @chipeta2017designing designed and tested the pedal-powered Gulper\n    pump in Mzuzu and estimated that a pit can be emptied in 1–2 hours\n    when trash content is low, a benchmark for the job durations recorded\n    here and one against which a half-hour disposal trip is substantial.\n4.  @chiposa2017characterization characterise pit latrines in peri-urban\n    Mzuzu, reporting that 90 % of households also dispose of domestic\n    waste in their pits, which helps explain the time spent on tasks such\n    as pulling out trash and affects how much material must be removed.\n5.  @burt2019costs estimate the cost of delivering pit emptying services\n    in Kigali, Rwanda, at different scales, giving a comparison point for\n    costs derived from the labour and travel times reported here.\n\n# References\n\n::: {#refs}\n:::\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}