{
  "hash": "45e4af4a1192a9743f23f5294042c120",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Total time spent on pit emptying jobs in Mzuzu, Malawi\"\nauthor:\n  - name: Padraic Casserly\n    email: pcasserly@ethz.ch\n    affiliations:\n      - name: Global Health Engineering, ETH Zürich\ndate: 2026-09-29\nbibliography: references.bib\nabstract: |\n  We use task-level timing data recorded with the Gulper Timer app during\n  ridealong observations of manual pit latrine emptying in Mzuzu, Malawi, to\n  quantify the total time spent on pit emptying jobs. Time is reported in two\n  ways: labour time (person-hours, the sum of all task durations across all\n  workers) and elapsed time (clock hours from the first to the last recorded\n  task of each job).\n---\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'dplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(readr)\nlibrary(ggplot2)\nlibrary(knitr)\n\ntasks <- read_csv(\"../../data/all_tasks.csv\", show_col_types = FALSE)\n\nfmt <- function(x, digits = 1) format(round(x, digits), nsmall = digits, big.mark = \",\", trim = TRUE)\n\njobs <- tasks |>\n  group_by(job_id) |>\n  summarise(\n    date = as.Date(substr(first(job_id), 1, 10)),\n    n_workers = n_distinct(gulper_id),\n    n_entries = n(),\n    labour_h = sum(duration_seconds) / 3600,\n    elapsed_h = as.numeric(max(entry_end_time) - min(entry_start_time)) / 3600,\n    .groups = \"drop\"\n  )\n\ntotal_labour_h <- sum(jobs$labour_h)\ntotal_elapsed_h <- sum(jobs$elapsed_h)\nn_jobs <- nrow(jobs)\nn_workers <- n_distinct(tasks$gulper_id)\nn_entries <- nrow(tasks)\n\nrest_h <- sum(tasks$duration_seconds[tasks$task == \"Rest\"]) / 3600\n```\n:::\n\n\n# Introduction\n\nTime-driven activity-based costing (TDABC) allocates costs to activities based\non the time resources spend on them. A first step is therefore to establish how\nmuch time is consumed by the service being costed. This short manuscript\nanswers the question: **What is the total amount of time spent on pit emptying\njobs?**\n\n# Data and methods\n\nThe dataset (`data/all_tasks.csv`) contains 10,784 task entries\nrecorded for 36 pit emptying jobs between\n08 May 2026 and 14 September 2026,\nperformed by 19 anonymised pit emptiers (\"gulpers\"). Each entry records\none worker performing one task (e.g. Fluidizing, Extraction, Rest) with a start\ntime, end time and duration in seconds.\n\nBecause several gulpers often work simultaneously on the same job, \"time spent\"\ncan be measured in two ways:\n\n- **Labour time (person-hours):** the sum of `duration_seconds` over all entries,\n  i.e. every worker's recorded time added together. This is the measure relevant\n  for TDABC, where labour capacity is the resource being costed.\n- **Elapsed time (clock hours):** for each job, the interval from the earliest\n  `entry_start_time` to the latest `entry_end_time`, summed across jobs. This\n  measures how long the jobs took on the calendar.\n\nAll recorded tasks, including Rest, Communication and in-job Travel (errands and\ntrips to the disposal site), are counted as time spent on the job. Travel from\nthe gulpers' base to the job site is not part of the task categories recorded.\n\nData checks: the file has no missing values except `subtask`, which is empty by\ndesign for the Rest and Disposal tasks. Recorded durations agree with the\ndifference between end and start times to within ±1 second (rounding). No job\ncrosses midnight, so elapsed time can be computed from clock times directly.\n\n# Results\n\nAcross the 36 observed jobs, gulpers spent a total of\n**509.0 person-hours** on pit emptying. The jobs took a total of\n**139.4 elapsed clock hours**, so on average\n3.7 gulpers' worth of time was being recorded\nat any moment of a job. Per job, the mean labour time was\n14.1 person-hours (median 11.0,\nrange 2.4–58.2) and the mean\nelapsed time was 3.9 hours (median\n3.4, range\n0.8–9.7).\n\n@tbl-task breaks the labour time down by main task. Rest is the largest single\ncategory (150.4 person-hours, 29.5 %\nof the total).\n\n\n::: {#tbl-task .cell tbl-cap='Labour time by main task, summed over all 36 jobs.'}\n\n```{.r .cell-code .hidden}\ntasks |>\n  group_by(Task = task) |>\n  summarise(\n    Entries = n(),\n    `Person-hours` = sum(duration_seconds) / 3600,\n    .groups = \"drop\"\n  ) |>\n  arrange(desc(`Person-hours`)) |>\n  mutate(`Share (%)` = 100 * `Person-hours` / sum(`Person-hours`)) |>\n  bind_rows(tibble(\n    Task = \"Total\", Entries = n_entries,\n    `Person-hours` = total_labour_h, `Share (%)` = 100\n  )) |>\n  kable(digits = 1, format.args = list(big.mark = \",\"))\n```\n\n::: {.cell-output-display}\n\n\n|Task            | Entries| Person-hours| Share (%)|\n|:---------------|-------:|------------:|---------:|\n|Rest            |   3,103|        150.4|      29.5|\n|Earthworks      |   1,098|         69.7|      13.7|\n|Fluidizing      |   1,470|         63.5|      12.5|\n|Equipment       |   1,353|         62.9|      12.4|\n|Extraction      |   1,381|         62.9|      12.4|\n|Travel          |     149|         36.2|       7.1|\n|Communication   |   1,342|         25.1|       4.9|\n|Superstructure  |     371|         16.6|       3.3|\n|Disposal        |     257|         14.2|       2.8|\n|Sludge handling |     260|          7.5|       1.5|\n|Total           |  10,784|        509.0|     100.0|\n\n\n:::\n:::\n\n\n@fig-task shows the same breakdown, with tasks coloured by the kind of work\nthey belong to.\n\n\n::: {#cell-fig-task .cell}\n\n```{.r .cell-code .hidden}\ntask_groups <- c(\n  Fluidizing        = \"Emptying the pit\",\n  Extraction        = \"Emptying the pit\",\n  `Sludge handling` = \"Emptying the pit\",\n  Disposal          = \"Emptying the pit\",\n  Earthworks        = \"Site and structure works\",\n  Superstructure    = \"Site and structure works\",\n  Equipment         = \"Support tasks\",\n  Communication     = \"Support tasks\",\n  Travel            = \"Support tasks\",\n  Rest              = \"Rest\"\n)\ngroup_colours <- c(\n  \"Emptying the pit\"         = \"#2a78d6\",\n  \"Site and structure works\" = \"#eb6834\",\n  \"Support tasks\"            = \"#1baf7a\",\n  \"Rest\"                     = \"#4a3aa7\"\n)\n\ntask_summary <- tasks |>\n  group_by(task) |>\n  summarise(hours = sum(duration_seconds) / 3600, .groups = \"drop\") |>\n  mutate(\n    share = 100 * hours / sum(hours),\n    group = factor(task_groups[task], levels = names(group_colours)),\n    task = reorder(task, hours),\n    label = paste0(fmt(hours), \" h (\", fmt(share), \" %)\")\n  )\n\nggplot(task_summary, aes(x = hours, y = task, fill = group)) +\n  geom_col(width = 0.72) +\n  geom_text(aes(label = label), hjust = -0.08, size = 3, colour = \"#52514e\") +\n  scale_fill_manual(values = group_colours, name = NULL) +\n  scale_x_continuous(expand = expansion(mult = c(0, 0.28))) +\n  labs(x = \"Labour time (person-hours)\", y = NULL) +\n  theme_minimal(base_size = 10) +\n  theme(\n    legend.position = \"top\",\n    legend.justification = \"left\",\n    legend.key.size = unit(0.4, \"cm\"),\n    panel.grid.major.y = element_blank(),\n    panel.grid.minor = element_blank(),\n    axis.text = element_text(colour = \"#52514e\"),\n    axis.text.y = element_text(colour = \"#0b0b0b\", size = 10)\n  )\n\ngroup_hours <- tapply(task_summary$hours, task_summary$group, sum)\n```\n\n::: {.cell-output-display}\n![Labour time by main task across all 36 jobs, coloured by activity group. Labels give person-hours and share of total labour time.](index_files/figure-docx/fig-task-1.png){#fig-task}\n:::\n:::\n\n\nGrouped this way, the tasks that directly empty the pit (fluidizing,\nextraction, sludge handling and disposal) account for\n148.1 person-hours\n(29.1 %), about the\nsame as Rest (150.4 person-hours). Support tasks take\n124.2 person-hours\n(24.4 %) and site and\nstructure works 86.3 person-hours\n(16.9 %).\n\n@fig-jobs shows the labour time of each job. Labour time varies widely between jobs;\n@tbl-jobs in the appendix lists the values for every job.\n\n\n::: {#cell-fig-jobs .cell}\n\n```{.r .cell-code .hidden}\njobs |>\n  mutate(job_id = factor(job_id, levels = rev(job_id))) |>\n  ggplot(aes(x = labour_h, y = job_id)) +\n  geom_col(fill = \"#2a78d6\", width = 0.7) +\n  geom_vline(xintercept = mean(jobs$labour_h), linetype = \"dashed\", colour = \"#52514e\") +\n  annotate(\"text\", x = mean(jobs$labour_h), y = n_jobs + 0.6,\n           label = paste0(\"mean \", fmt(mean(jobs$labour_h)), \" h\"),\n           hjust = -0.05, size = 3, colour = \"#52514e\") +\n  scale_x_continuous(expand = expansion(mult = c(0, 0.05))) +\n  coord_cartesian(clip = \"off\") +\n  labs(x = \"Labour time (person-hours)\", y = NULL) +\n  theme_minimal(base_size = 10) +\n  theme(\n    panel.grid.major.y = element_blank(),\n    panel.grid.minor = element_blank(),\n    axis.text = element_text(colour = \"#52514e\"),\n    plot.margin = margin(12, 8, 4, 4)\n  )\n```\n\n::: {.cell-output-display}\n![Labour time (person-hours) per pit emptying job, ordered by date.](index_files/figure-docx/fig-jobs-1.png){#fig-jobs}\n:::\n:::\n\n\n# Conclusion\n\nThe total amount of time spent on the 36 observed pit emptying jobs was\n**509.0 person-hours** of recorded labour\n(139.4 elapsed clock hours). For TDABC purposes the\nperson-hour figure is the relevant quantity, since it reflects the labour\ncapacity consumed by the service.\n\n# Appendix A: Job-level results {.appendix}\n\n\n::: {#tbl-jobs .cell tbl-cap='Workers, labour time and elapsed time for each job.'}\n\n```{.r .cell-code .hidden}\njobs |>\n  transmute(\n    Job = job_id,\n    Gulpers = n_workers,\n    Entries = n_entries,\n    `Labour (person-h)` = labour_h,\n    `Elapsed (h)` = elapsed_h\n  ) |>\n  bind_rows(tibble(\n    Job = \"Total\", Gulpers = n_workers, Entries = n_entries,\n    `Labour (person-h)` = total_labour_h, `Elapsed (h)` = total_elapsed_h\n  )) |>\n  kable(digits = 1, format.args = list(big.mark = \",\"))\n```\n\n::: {.cell-output-display}\n\n\n|Job           | Gulpers| Entries| Labour (person-h)| Elapsed (h)|\n|:-------------|-------:|-------:|-----------------:|-----------:|\n|2026-05-08_01 |       2|     162|               4.9|         2.5|\n|2026-05-21_01 |       2|     121|               2.7|         1.5|\n|2026-05-31_01 |       1|      91|               2.8|         2.9|\n|2026-06-12_01 |       4|     375|              12.0|         3.1|\n|2026-06-13_01 |       8|   1,139|              26.5|         4.6|\n|2026-06-13_03 |       3|     241|               7.0|         2.3|\n|2026-06-14_02 |       7|   1,187|              39.3|         8.3|\n|2026-06-16_01 |       3|     199|              10.9|         3.7|\n|2026-06-18_01 |       3|      71|               5.2|         1.7|\n|2026-06-22_02 |       4|     159|              11.2|         2.8|\n|2026-06-29_01 |       4|     228|              21.1|         6.1|\n|2026-07-03_02 |       4|     295|              16.6|         4.4|\n|2026-07-09_01 |       4|     340|              18.5|         5.5|\n|2026-07-13_01 |       3|     175|               7.9|         2.6|\n|2026-07-27_03 |       4|     511|              14.9|         4.5|\n|2026-07-29_01 |       3|     347|               6.6|         2.2|\n|2026-07-31_01 |       4|     456|              14.3|         3.6|\n|2026-08-03_01 |       3|     199|              13.7|         4.6|\n|2026-08-08_01 |       4|     651|              35.3|         9.7|\n|2026-08-11_03 |       4|     404|              15.8|         4.0|\n|2026-08-20_02 |       4|     290|              21.0|         6.2|\n|2026-08-20_03 |       4|     270|              10.1|         2.5|\n|2026-08-22_01 |       4|     224|               6.9|         2.0|\n|2026-08-22_02 |       4|     375|              15.7|         3.9|\n|2026-08-23_02 |       4|     213|              14.3|         3.6|\n|2026-08-25_02 |       3|      35|               2.4|         0.8|\n|2026-08-25_03 |       3|      74|               2.6|         0.9|\n|2026-08-27_02 |       4|     220|              10.3|         4.4|\n|2026-08-27_03 |       3|     151|               9.0|         3.0|\n|2026-08-28_02 |       3|     224|               8.5|         2.8|\n|2026-09-03_03 |       7|     630|              58.2|         8.4|\n|2026-09-08_01 |       4|     377|              33.4|         8.4|\n|2026-09-13_03 |       2|      54|               2.4|         1.2|\n|2026-09-13_05 |       2|     103|               5.7|         2.9|\n|2026-09-14_01 |       3|      92|               7.9|         3.2|\n|2026-09-14_02 |       3|     101|              13.7|         4.6|\n|Total         |      19|  10,784|             509.0|       139.4|\n\n\n:::\n:::\n\n\n# Appendix B: Relevant literature {.appendix}\n\nThe five references in the author's Zotero library most relevant to this\ndataset, with one sentence on why each matters here:\n\n1. @yesaya2021cost apply time-driven activity-based costing to compost\n   production in Blantyre, Malawi, making it the closest methodological\n   precedent for turning task-level timing data like these into activity costs.\n2. @wilcox2026formal analyse the costs of 23 formal manual emptying providers in\n   Malawi and Uganda and find labour is what makes manual emptying expensive,\n   which is why the person-hours measured here are the key input for costing.\n3. @chipeta2017designing designed and tested the pedal-powered Gulper pump in\n   Mzuzu and estimated that a pit can be emptied in 1–2 hours when trash\n   content is low, a benchmark for the job durations recorded here.\n4. @chiposa2017characterization characterise pit latrines in peri-urban Mzuzu,\n   reporting that 90 % of households also dispose of domestic waste in their\n   pits, which helps explain the time spent on tasks such as pulling out trash.\n5. @burt2019costs estimate the cost of delivering pit emptying services in\n   Kigali, Rwanda, at different scales, giving a comparison point for costs\n   derived from the labour time reported here.\n\n# References\n\n::: {#refs}\n:::\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}